In [1]:
import pandas as pd

In [2]:
team_to_id = {"ANA":197, "ARI":198, "BOS":199, "BUF":200, "CAR":201, "CBJ":202, "CGY":203, "CHI":204, "COL":205, "DAL":206, "DET":207, "EDM":208, "FLA":209, "LAK":210, "MIN":211, "MTL":212, "NJD":213, "NSH":214, "NYI":215, "NYR":216, "OTT":217, "PHI":218, "PIT":219, "SEA":220, "SJS":221, "STL":222, "TBL":223, "TOR":224, "VAN":225, "VGK":226, "WPG":227, "WSH":228}

In [10]:
all_player_df = pd.read_csv('all_teams.csv', sep=',', header=0, dtype = str)[['season','gameId','playerTeam','opposingTeam','home_or_away','gameDate']]
all_player_df = all_player_df.drop_duplicates()
all_player_df['playerTeam'] = all_player_df['playerTeam'].replace('L.A','LAK')
all_player_df['playerTeam'] = all_player_df['playerTeam'].replace('N.J','NJD')
all_player_df['playerTeam'] = all_player_df['playerTeam'].replace('S.J','SJS')
all_player_df['playerTeam'] = all_player_df['playerTeam'].replace('T.B','TBL')
all_player_df['opposingTeam'] = all_player_df['opposingTeam'].replace('L.A','LAK')
all_player_df['opposingTeam'] = all_player_df['opposingTeam'].replace('N.J','NJD')
all_player_df['opposingTeam'] = all_player_df['opposingTeam'].replace('S.J','SJS')
all_player_df['opposingTeam'] = all_player_df['opposingTeam'].replace('T.B','TBL')
# print(all_player_df[all_player_df.team=="ATL"].index)
all_player_df = all_player_df.drop(all_player_df[all_player_df.playerTeam=="ATL"].index)
all_player_df = all_player_df.drop(all_player_df[all_player_df.opposingTeam=="ATL"].index)
# all_player_df = all_player_df.drop([ 184,  314,  554,  595,  938,  972, 1002, 1048, 1472, 1494, 1822,
#             1959, 2211, 2432, 2566, 2921])
all_player_df

       season      gameId playerTeam opposingTeam home_or_away  gameDate
0        2008  2008020001        NYR          TBL         AWAY  20081004
5        2008  2008020003        NYR          TBL         HOME  20081005
10       2008  2008020010        NYR          CHI         HOME  20081010
15       2008  2008020019        NYR          PHI         AWAY  20081011
20       2008  2008020034        NYR          NJD         HOME  20081013
...       ...         ...        ...          ...          ...       ...
185185   2015  2015030185        LAK          SJS         HOME  20160422
185190   2017  2017030171        LAK          VGK         AWAY  20180411
185195   2017  2017030172        LAK          VGK         AWAY  20180413
185200   2017  2017030173        LAK          VGK         HOME  20180415
185205   2017  2017030174        LAK          VGK         HOME  20180417

[36550 rows x 6 columns]

In [18]:
sample = all_player_df[all_player_df.playerTeam=="ANA"]
sample = sample[sample.opposingTeam == "BOS"]
# sample = sample[sample.season == 2014]
sample

      season      gameId playerTeam opposingTeam home_or_away  gameDate
58950   2008  2008020908        ANA          BOS         AWAY  20090226
59060   2009  2009020035        ANA          BOS         AWAY  20091008
59280   2009  2009020692        ANA          BOS         HOME  20100113
59640   2010  2010020488        ANA          BOS         AWAY  20101220
60245   2011  2011021132        ANA          BOS         HOME  20120325
60585   2013  2013020188        ANA          BOS         AWAY  20131031
60740   2013  2013020655        ANA          BOS         HOME  20140107
61055   2014  2014020361        ANA          BOS         HOME  20141201
61305   2014  2014021101        ANA          BOS         AWAY  20150326
61575   2015  2015020731        ANA          BOS         AWAY  20160126
61690   2015  2015021066        ANA          BOS         HOME  20160318
61900   2016  2016020445        ANA          BOS         AWAY  20161215
62055   2016  2016020893        ANA          BOS         HOME  20170222
62245   2017  2017020277        ANA          BOS         HOME  20171115
62410   2017  2017020761        ANA          BOS         AWAY  20180130
62750   2018  2018020530        ANA          BOS         AWAY  20181220
62855   2018  2018020891        ANA          BOS         HOME  20190215
63005   2019  2019020078        ANA          BOS         AWAY  20191014
63830   2021  2021020737        ANA          BOS         AWAY  20220124
63890   2021  2021020859        ANA          BOS         HOME  20220301
64045   2022  2022020059        ANA          BOS         AWAY  20221020
64225   2022  2022020644        ANA          BOS         HOME  20230108

In [ ]:
output_string = ""

In [ ]:
sample = all_player_df.loc[[5,200,400,1000,1300,1600,1900,2300,2500,2900]]
sample

,playerId,name,position,team,birthDate,weight,height,nationality,shootsCatches,primaryNumber,primaryPosition
5,8469534,Aaron Johnson,D,BOS,1983-04-30,204.0,"6' 1""",CAN,L,72,D
200,8479447,Anthony Greco,R,NYR,1993-09-30,176.0,"5' 10""",USA,R,76,R
400,8475757,Brett Bulmer,R,MIN,1992-04-26,212.0,"6' 4""",CAN,R,54,R
1000,8473712,Frazer McLaren,L,TOR,1987-10-29,230.0,"6' 5""",CAN,L,68,L
1300,8468510,Jeff Taffe,L,MIN,1981-02-19,207.0,"6' 3""",USA,L,23,L
1600,8469598,Kevin Bieksa,D,ANA,1981-06-16,197.0,"6' 1""",CAN,R,3,D
1900,8470121,Matt Greene,D,LAK,1983-05-13,236.0,"6' 3""",USA,R,2,D
2300,8476200,Paul Thompson,R,FLA,1988-11-30,200.0,"6' 1""",USA,R,15,R
2500,8468011,Ryan Miller,G,ANA,1980-07-17,168.0,"6' 2""",USA,L,30,G
2900,8478407,Vince Dunn,D,SEA,1996-10-29,203.0,"6' 0""",CAN,L,29,D

In [ ]:
def inch_to_cm(height):
  foot = int(height[0])
  inch = int(height[2:-1])
  return(int((12*foot+inch)*2.58))

In [ ]:
for index, row in sample.iterrows():
  output_string += "\t("+row['playerId']+", '"+row['name']+"', '"+row['birthDate']+"', "+row['weight'][0:3]+", "+str(inch_to_cm(row['height']))+", '"+row['team']+"', NULL, "+str(2023-int(row['birthDate'][0:4]))+", '"+row['position']+"'),\n"

In [ ]:
print(output_string)

	(8469534, 'Aaron Johnson', '1983-04-30', 204, 188, 'BOS', NULL, 40, 'D'),
	(8479447, 'Anthony Greco', '1993-09-30', 176, 180, 'NYR', NULL, 30, 'R'),
	(8475757, 'Brett Bulmer', '1992-04-26', 212, 196, 'MIN', NULL, 31, 'R'),
	(8473712, 'Frazer McLaren', '1987-10-29', 230, 198, 'TOR', NULL, 36, 'L'),
	(8468510, 'Jeff Taffe', '1981-02-19', 207, 193, 'MIN', NULL, 42, 'L'),
	(8469598, 'Kevin Bieksa', '1981-06-16', 197, 188, 'ANA', NULL, 42, 'D'),
	(8470121, 'Matt Greene', '1983-05-13', 236, 193, 'LAK', NULL, 40, 'D'),
	(8476200, 'Paul Thompson', '1988-11-30', 200, 188, 'FLA', NULL, 35, 'R'),
	(8468011, 'Ryan Miller', '1980-07-17', 168, 190, 'ANA', NULL, 43, 'G'),
	(8478407, 'Vince Dunn', '1996-10-29', 203, 185, 'SEA', NULL, 27, 'D'),