In [48]:
import pandas as pd

In [59]:
all_player_df = pd.read_csv('allPlayersLookup.csv', sep=',', header=0, dtype = str)
all_player_df['team'] = all_player_df['team'].replace('L.A','LAK')
all_player_df['team'] = all_player_df['team'].replace('N.J','NJD')
all_player_df['team'] = all_player_df['team'].replace('S.J','SJS')
all_player_df['team'] = all_player_df['team'].replace('T.B','TBL')
# print(all_player_df[all_player_df.team=="ATL"].index)
all_player_df = all_player_df.drop(all_player_df[all_player_df.team=="ATL"].index)
# all_player_df = all_player_df.drop([ 184,  314,  554,  595,  938,  972, 1002, 1048, 1472, 1494, 1822,
#             1959, 2211, 2432, 2566, 2921])
all_player_df

,playerId,name,position,team,birthDate,weight,height,nationality,shootsCatches,primaryNumber,primaryPosition
0,8478421,A.J. Greer,L,BOS,1996-12-14,210.0,"6' 3""",CAN,L,24,L
1,8477180,Aaron Dell,G,SJS,1989-05-04,205.0,"6' 0""",CAN,L,30,G
2,8465992,Aaron Downey,R,DET,1974-08-27,215.0,"6' 1""",CAN,R,44,R
3,8477932,Aaron Ekblad,D,FLA,1996-02-07,220.0,"6' 4""",CAN,R,5,D
4,8471451,Aaron Gagnon,C,WPG,1986-04-24,186.0,"5' 11""",CAN,R,21,C
...,...,...,...,...,...,...,...,...,...,...,...
2986,8475876,Zane McIntyre,G,BOS,1992-08-20,206.0,"6' 2""",USA,L,31,G
2987,8469760,Zbynek Michalek,D,ARI,1982-12-23,210.0,"6' 2""",CZE,R,4,D
2988,8465009,Zdeno Chara,D,NYI,1977-03-18,250.0,"6' 9""",SVK,L,33,D
2989,8476878,Zemgus Girgensons,L,BUF,1994-01-05,211.0,"6' 2""",LVA,L,28,C
2990,8469820,Zenon Konopka,C,BUF,1981-01-02,213.0,"6' 0""",CAN,L,24,C

In [60]:
teamdf = all_player_df[['team']].drop_duplicates()
teamdf.sort_values(by=['team'])

    team
11   ANA
7    ARI
0    BOS
39   BUF
8    CAR
16   CBJ
37   CGY
48   CHI
6    COL
9    DAL
2    DET
45   EDM
3    FLA
42   LAK
15   MIN
52   MTL
31   NJD
33   NSH
35   NYI
23   NYR
24   OTT
25   PHI
28   PIT
29   SEA
1    SJS
100  STL
55   TBL
57   TOR
13   VAN
40   VGK
4    WPG
10   WSH

In [61]:
output_string = ""

In [67]:
sample = all_player_df.loc[[5,200,400,800,1300,1600,1900,2300,2500,2900]]
sample

,playerId,name,position,team,birthDate,weight,height,nationality,shootsCatches,primaryNumber,primaryPosition
5,8469534,Aaron Johnson,D,BOS,1983-04-30,204.0,"6' 1""",CAN,L,72,D
200,8479447,Anthony Greco,R,NYR,1993-09-30,176.0,"5' 10""",USA,R,76,R
400,8475757,Brett Bulmer,R,MIN,1992-04-26,212.0,"6' 4""",CAN,R,54,R
800,8470189,David Van Der Gulik,L,LAK,1983-04-20,173.0,"5' 10""",CAN,L,36,L
1300,8468510,Jeff Taffe,L,MIN,1981-02-19,207.0,"6' 3""",USA,L,23,L
1600,8469598,Kevin Bieksa,D,ANA,1981-06-16,197.0,"6' 1""",CAN,R,3,D
1900,8470121,Matt Greene,D,LAK,1983-05-13,236.0,"6' 3""",USA,R,2,D
2300,8476200,Paul Thompson,R,FLA,1988-11-30,200.0,"6' 1""",USA,R,15,R
2500,8468011,Ryan Miller,G,ANA,1980-07-17,168.0,"6' 2""",USA,L,30,G
2900,8478407,Vince Dunn,D,SEA,1996-10-29,203.0,"6' 0""",CAN,L,29,D

In [63]:
def inch_to_cm(height):
  foot = int(height[0])
  inch = int(height[2:-1])
  return(int((12*foot+inch)*2.58))

In [64]:
for index, row in sample.iterrows():
  output_string += "\t("+row['playerId']+", '"+row['name']+"', '"+row['birthDate']+"', "+row['weight'][0:3]+", "+str(inch_to_cm(row['height']))+", '"+row['team']+"', NULL, "+str(2023-int(row['birthDate'][0:4]))+", '"+row['position']+"'),\n"

In [68]:
print(output_string)

	(8469534, 'Aaron Johnson', '1983-04-30', 204, 188, 'BOS', NULL, 40, 'D'),
	(8479447, 'Anthony Greco', '1993-09-30', 176, 180, 'NYR', NULL, 30, 'R'),
	(8475757, 'Brett Bulmer', '1992-04-26', 212, 196, 'MIN', NULL, 31, 'R'),
	(8473712, 'Frazer McLaren', '1987-10-29', 230, 198, 'TOR', NULL, 36, 'L'),
	(8468510, 'Jeff Taffe', '1981-02-19', 207, 193, 'MIN', NULL, 42, 'L'),
	(8469598, 'Kevin Bieksa', '1981-06-16', 197, 188, 'ANA', NULL, 42, 'D'),
	(8470121, 'Matt Greene', '1983-05-13', 236, 193, 'LAK', NULL, 40, 'D'),
	(8476200, 'Paul Thompson', '1988-11-30', 200, 188, 'FLA', NULL, 35, 'R'),
	(8468011, 'Ryan Miller', '1980-07-17', 168, 190, 'ANA', NULL, 43, 'G'),
	(8478407, 'Vince Dunn', '1996-10-29', 203, 185, 'SEA', NULL, 27, 'D'),